[#thomas, short="Life of Thomas Camm"]
== Memoir of Thomas Camm, Minister of the Gospel, of Camsgill, In Westmoreland.

Thomas Camm, husband of Anne Camm, was born at Camsgill, in Westmoreland,
in the year 1641.
Both his parents were members of the religious Society of Friends,
distinguished for their piety, integrity and godly concern for their children.
Besides the advantage of their counsel and of being
instructed in the religious principles of his parents,
the circumspection of their example made a lasting impression on his youthful mind.
Through these means, and the visitations of Divine Grace,
he was imbued with religious sentiments from childhood,
and took delight in the company of the most serious people,
earnestly seeking after heaven and heavenly things.
As he grew up, his understanding was divinely enlightened to perceive,
that great as was the blessing of a guarded education in sound religious principles,
yet it would not be availing without the heart was regenerated
and sanctified by the operations of the Holy Spirit.

Being thus mercifully visited, he counted nothing too dear to part with,
but cheerfully took up his cross, and followed his Divine Master.
He was often engaged in retirement and reverent waiting on the Lord to know his will;
and as he endured the necessary baptisms,
at length experienced that purification of heart which his soul longed after.

Having witnessed the blessed fruits of obedience to the Spirit of Christ,
he was called to testify to others what God had done for his soul.
The Lord who called him to the work of the ministry, qualified him therefor;
enduing him with heavenly wisdom and discernment,
to divide the word of life to the states of those among whom he laboured.
His doctrine was sound, not delivered in the enticing words, which man`'s wisdom teaches,
but in the authority of heavenly power,
by which he was made instrumental to awaken and turn many into the way of righteousness.
He was freely given up to serve the Lord--travelling
extensively to proclaim the glad tidings of salvation,
and to call people from a dependance on external performances,
to the heart-changing power of Christ`'s spirit in themselves.
He also had his share of sufferings, by imprisonments, spoiling of goods,
mockings and scoffings from the ungodly,
and the unfaithfulness and reviling of false brethren,
which he bore with meekness and patience.

In the year 1674, he was sued for small tithes and oblations, by John Ormrod,
the priest of Burton, and by a warrant obtained for the purpose,
was imprisoned at Kendal.
Here he was detained in close confinement for nearly three years;
and afterwards was again thrown into the county jail at Appleby,
where he lay for six years.

In 1678, after the last conventicle act came in force,
a justice of the peace sent informers to a meeting of Friends held at Ackonthwaite,
and upon their evidence convicted several persons, without summoning them before him,
or examining into the case.
He immediately issued warrants of distraint against them, unseen and unheard,
and sent the officers to levy on their property.
In virtue of this illegal and unrighteous proceeding, nine head of cattle,
and fifty-five sheep were taken from Thomas Camm, for preaching at the meeting.

When the officers complained to the justice that they could not sell some of the cattle,
many persons being unwilling to buy what was so dishonestly obtained,
he charged them to sell for any price they could obtain,
and seize more from Thomas to make up the deficiency, telling them,
that if they did not raise all the fine from him,
they should pay it out of their own pockets.

Shortly after this another distraint was made upon his property,
by warrant from the same justice,
professedly for the fines of a preacher at one of their meetings,
who was declared in the warrant to have fled the county and his residence to be unknown.
So far was this from being true, that Thomas Dowcra, the preacher alluded to,
went to the justice`'s house after the meeting, and left his name,
with information that he lived at Swarthmore, near Ulverstone, in Lancashire;
that he was of ability to suffer for his own fine,
and therefore desired it might not be imposed upon others.
But Justice Wilson and his aids, regardless of this,
chose to seek their gain from one nearer at hand,
and from whom they could more conveniently wrest their unjust demands.

These sufferings, however oppressive and illegal,
Thomas Camm endured with fortitude and patience.
Instead of shrinking from the discharge of duty in consequence of these trials,
he nobly maintained his ground, rejoicing that he was counted worthy,
not only to believe in Christ, but also to suffer for his name sake.

He was well qualified for administering the Discipline of the church,
being himself a good example in conduct and conversation,
and fervent in his labours to promote among Friends,
a demeanour answerable to their high profession.
Actuated by a well tempered and godly zeal,
he steadfastly withstood that contentious spirit,
which sought to lay waste the tender care of Friends over each other,
and to foment discord and divisions in the church.
Yet with meekness of wisdom, as a tender father, he encouraged the fearful,
strengthened the weak, and comforted the mourners,
proving himself a faithful steward of the manifold grace of God.
Being a man of peace, he laboured to promote it among men of all ranks and classes;
and his kind and gentle disposition won for him the
respect of the virtuous wherever he was known.

When far advanced in years, and afflicted with the infirmities consequent on old age,
and the sufferings and hardships he had endured,
his zeal for religion and his unfeigned love for the brethren, abated not;
but he engaged in repeated visits to different parts of the nation.

The last journey of this kind which he performed, was into Lancashire, Yorkshire,
and through his native county of Westmoreland;
from which he returned on the 17th of the eleventh month, 1707, O. S.,
to the residence of his son-in-law, John Moore, at Eldworth.

Soon after reaching this place,
he had a return of a disorder to which he had for years been subject,
and the pain being violent he could take but little food, nor obtain natural sleep,
the lack of which rapidly impaired his strength.
He was however favoured with resignation;
and in the prospect of a glorious immortality could rejoicingly say,
"`to me to live is Christ, and to die is gain.`"

He often remarked, "`I neither desire to live nor to die, but am well contented,
however it shall please the Lord to order it.`"
"`If the Lord see fit, and has any further service for me to do,
it is easy for him to raise me up again--but his will be done--I am very well content,
I bless the Lord.`"
As he drew towards the close of life,
the retrospect of his past labours and sufferings in the cause of his Divine Master,
afforded him comfort; "`I have great peace and satisfaction,`" said he on one occasion,
"`in that I have done the will of God.
I do not know that I have much more to do--the time of my departure seems to draw nigh,
and I am well satisfied.
I bless the Lord that I can say with the apostle, '`I have fought a good fight;
I have finished my course;
I have kept the faith--henceforth there is laid up for me a crown of righteousness,
which the Lord the righteous Judge shall give me at that day, and not to me only,
but to them also that love his appearing.`'`"

Sitting alone one day in his chamber, his son-in-law came in and asked how he felt,
to which he replied, "`I am weak in body, but strong in the inner man;
blessed be the Lord, who has been my support and strength hitherto.`"
Soon after he proceeded; "`I have been pondering in my mind,
and meditating on the unspeakable mercies and loving kindnesses of God,
extended to me all my life long, even to this very day.--Wonderful, indeed,
that such a poor feeble creature as I,
should be enabled to hold out through the many trials, travels and sufferings,
both inward and outward, which have fallen to my lot.
It has indeed been the Lord`'s doing, who is, and has all along been,
my buckler and my shield.
He shall have the praise and glory of all, for He alone is worthy of it,
forever and forever more.`"

As he was walking over the floor of his chamber one evening,
leaning on his son-in-law`'s arm, he perceived his limbs to tremble under him,
from increased weakness; on which he remarked, "`Dear John,
when the pillars of the house begin to tremble, there is feebleness indeed;--but,
blessed are they who, when this earthly tabernacle is ready to be dissolved,
do assuredly know that they have a habitation eternal in the heavens,
whose builder and maker the Lord is--of which, for my part, I bless the Lord,
I am well satisfied.`"

About a week before his decease, several of his grandchildren being in the room with him,
he said to them, "`I think I must now leave you.
If the Lord had seen fit to spare me a little longer,
I might have been of service to you in counsel and advice.
But the Lord, the great and wise Counsellor, will never fail you in counsel,
as you have your eye to Him above all things.
I love you entirely, and may the blessing of the Lord rest upon you, if it be his will.`"

On another occasion he said, "`Faith and patience, hope and charity,
are excellent virtues; may the Lord endue his children more and more therewith.`"
His weakness being so great as to make it difficult to get his clothes on or off,
he remarked to those who were assisting him, "`Dear children,
you have a great deal of trouble about me,--may the Lord be your reward.
You will see that a little time will put an end to all these troubles,
and a happy end it will be for me--I doubt it not at all.`"

His eldest grand-daughter standing by him, he took her hand and said, "`Dear Anna,
the Lord will reward you for your care and pains about me.`"
Observing that she was much affected at the prospect of losing so near and dear a relative,
he proceeded, "`Death will not be denied--but it will be well with me;
the enemy cannot touch me.
The Lord who has been with me,
and borne up my spirit through and over all the various exercises and trials of my time,
will be with me to the end--there is no doubt of it.`"

The heavenly tranquillity and joy which he was permitted to feel,
occasioned him at times to break forth in praises and thanksgivings to the Most High,
his heart appearing to be filled with melody.
On one occasion he said, "`I have served the Lord in sincerity with all my heart,
and with all my soul, and with all my strength;
hallelujah--hallelujah--hallelujah to his name;`"--and so went on magnifying the Lord,
to the tendering of those present.
Afterward he called on his son-in-law and some others present, saying, "`Bear me record,
that I die in perfect unity with the brethren.
My love is as firm and true as ever, in our Lord Jesus Christ,
the Author of our salvation.`"
On being asked how he was, he would reply, "`Weak of body,
but strong in the Lord--in Abraham`'s bosom there is sweet repose.`"

Two days before he died, appearing very faint, some wine was given him,
as a cordial to revive his declining strength; but his stomach would not retain it;
on which he cheerfully said to his son-in-law, "`You see these things will not do;
but one cup of new wine in the heavenly kingdom with
my dear and blessed Lord and Saviour Jesus Christ,
will make up all.`"

His end being now apparently very near, he said, "`I hope the Lord,
who has been my helper in many straits and difficulties, will also help me now.`"
Taking one of his little grandchildren upon his knees,
he affectionately embraced and kissed her, saying,
"`God Almighty bless you--the God of Abraham, of Isaac, and of Jacob,
bless you and make you happy, if it be his will.`"
After this he laid down and continued in a very calm and sweet frame of mind,
and gently drawing his breath shorter, without any struggle or disturbance,
his redeemed spirit departed to the mansions of eternal glory and blessedness,
on the 13th of the first month, 1707-8. He was in the sixty-seventh year of his age.

On the 16th of the same month,
his remains were interred in Friends`' burial-ground at Park-end, Preston Patrick,
near Camsgill,
accompanied by a large concourse of people out of several adjoining counties,
who assembled on the occasion,
with evident marks of sorrow for the loss of so worthy and useful a man.
